spring.application.name=optionsfinder
spring.jackson.time-zone=Europe/Berlin
mock.sources.internal-flights.latency-ms=0
mock.sources.internal-flights.outcome=NORMAL
mock.sources.internal-flights.timeout-delay-ms=3000
mock.sources.external-flights.latency-ms=0
mock.sources.external-flights.outcome=NORMAL
mock.sources.external-flights.timeout-delay-ms=3000
mock.sources.trains.latency-ms=0
mock.sources.trains.outcome=NORMAL
mock.sources.trains.timeout-delay-ms=60000
